"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-25 15:55:06.137150
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "capture",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'pending' AND snapshot_id IS NULL AND error IS NULL AND captured_at IS NULL) OR (status = 'succeeded' AND snapshot_id IS NOT NULL AND error IS NULL AND captured_at IS NOT NULL) OR (status = 'failed' AND error IS NOT NULL AND ((snapshot_id IS NULL AND captured_at IS NULL) OR (snapshot_id IS NOT NULL AND captured_at IS NOT NULL)))",
            name="capture_outcome",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed')", name="capture_status"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "url"),
    )
    op.create_table(
        "page",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("organization", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["capture_id"], ["capture.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capture_id", "dataset"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("page")
    op.drop_table("capture")
    op.drop_table("run")
    # ### end Alembic commands ###
