"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-25 16:40:34.890113
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("error_stage", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'pending' AND snapshot_id IS NULL AND error_stage IS NULL AND error IS NULL AND captured_at IS NULL AND extracted_at IS NULL) OR (status = 'succeeded' AND snapshot_id IS NOT NULL AND error_stage IS NULL AND error IS NULL AND captured_at IS NOT NULL AND extracted_at IS NOT NULL) OR (status = 'failed' AND error_stage IS NOT NULL AND error IS NOT NULL AND extracted_at IS NULL AND ((snapshot_id IS NULL AND captured_at IS NULL) OR (snapshot_id IS NOT NULL AND captured_at IS NOT NULL)))",
            name="extraction_outcome",
        ),
        sa.CheckConstraint(
            "error_stage IS NULL OR error_stage IN ('capture', 'extract')",
            name="extraction_error_stage",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed')", name="extraction_status"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "url"),
    )
    op.create_table(
        "holder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("person_name", sa.Text(), nullable=False),
        sa.Column("position_name", sa.Text(), nullable=False),
        sa.Column("person_dob", sa.Text(), nullable=True),
        sa.Column("person_bio", sa.Text(), nullable=True),
        sa.Column("person_countries", sa.JSON(), nullable=False),
        sa.Column("position_organization", sa.Text(), nullable=True),
        sa.Column("position_description", sa.Text(), nullable=True),
        sa.Column("position_jurisdiction", sa.Text(), nullable=True),
        sa.Column("position_start_date", sa.Text(), nullable=True),
        sa.Column("position_end_date", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["extraction.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "page",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("organization", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["extraction.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extraction_id", "dataset"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("page")
    op.drop_table("holder")
    op.drop_table("extraction")
    op.drop_table("run")
    # ### end Alembic commands ###
